import { Arrow, Shell } from "@/components/SiteChrome";

const today=["Driver availability and location","Selected load opportunities","Clear route, timing and equipment details","Driver bid submission","Operational notifications and updates"];
const development=["Dispatcher intelligence command center","Fleet and capacity intelligence","Automated broker communication intelligence","Connected operational and business analytics","Workflow automation and platform integrations"];
const vision=["Predictive market intelligence","Continuous business and margin intelligence","AI decision engine across the operation","Autonomous routine workflows","An AI operating copilot for independent freight"];

export default function Platform(){return <Shell><section className="page-hero wrap"><span className="hero-tag"><i/> THE LOADWISE OPERATING SYSTEM</span><h1>Intelligence for every layer<br/><em>of independent freight.</em></h1><p>The platform connects operational signals, dispatch decisions, fleet capacity, market context and business performance through one evolving AI intelligence layer.</p><div><a className="btn" href="#today">Explore the platform <Arrow/></a><a className="link" href="/contact#application">Driver application →</a></div></section>
  <section className="platform-canvas"><div className="wrap"><div className="section-heading light-copy"><span className="section-no light">THE INTELLIGENCE ARCHITECTURE</span><h2>One AI decision engine.<br/>A connected operating system.</h2><p>Each intelligence domain understands part of the business. The platform connects them into a shared operational context that no isolated application can create.</p></div><div className="platform-map"><div className="platform-node main-node"><small>LOADWISE AI</small><strong>Decision<br/>Engine</strong></div>{["Connected operations","Dispatcher intelligence","Fleet intelligence","Market intelligence","Business intelligence","Future AI copilot"].map((x,i)=><div className={`platform-node n${i+1}`} key={x}><span>0{i+1}</span><b>{x}</b></div>)}</div></div></section>
  <section className="status-section wrap" id="today"><div className="status-intro"><span className="section-no">PRODUCT STATUS</span><h2>Ambitious about the future.<br/>Clear about today.</h2><p>LoadWise is evolving in deliberate stages. Capabilities are labeled by their real product status.</p></div><div className="status-columns"><Status label="AVAILABLE TODAY" title="The first operational layer" items={today} kind="now"/><Status label="IN DEVELOPMENT" title="The connected platform" items={development} kind="next"/><Status label="LONG-TERM VISION" title="The intelligent operation" items={vision} kind="future"/></div></section>
  <section className="feature-band"><div className="wrap feature-split"><div><span className="section-no light">AI ENGINE</span><h2>AI that removes work—not adds another screen.</h2><p>The LoadWise intelligence layer is designed to observe operational signals, understand context, recommend action and automate repeatable workflows.</p></div><ol><li><b>Observe</b><span>Loads, vehicles, drivers, communication and markets.</span></li><li><b>Understand</b><span>Turn disconnected data into operational meaning.</span></li><li><b>Recommend</b><span>Surface fewer, more relevant paths forward.</span></li><li><b>Automate</b><span>Handle routine work before it becomes a task.</span></li></ol></div></section>
  <section className="security wrap"><span className="section-no">SECURITY & INTEGRATIONS</span><div><h2>Designed for trust.<br/>Built to connect.</h2><p>As LoadWise expands, security, permissioned access and practical integrations will remain part of the platform foundation—not afterthoughts.</p></div><div className="security-grid"><article><span>01</span><h3>Operational privacy</h3><p>Information is collected for explicit operational purposes and handled with controlled access.</p></article><article><span>02</span><h3>Reliable architecture</h3><p>A scalable foundation prepared for growing fleets, data volumes and workflows.</p></article><article><span>03</span><h3>Open ecosystem</h3><p>A long-term integration approach built around the tools freight operators already depend on.</p></article></div></section>
  <section className="access" id="roadmap"><div className="wrap final-cta"><span className="section-no light">DRIVER APPLICATIONS</span><h2>Take the first step with<br/>Liberty Haul & Logistics.</h2><p>Submit a short application now. Full onboarding and remaining documents can follow later.</p><a className="btn" href="/contact#application">Apply to drive <Arrow/></a></div></section></Shell>}

function Status({label,title,items,kind}:{label:string,title:string,items:string[],kind:string}){return <article className={`status-card ${kind}`}><span>{label}</span><h3>{title}</h3><ul>{items.map(x=><li key={x}>{x}</li>)}</ul></article>}
